language: ruby
cache: bundler
before_install: gem install bundler -v 1.11
rvm:
  - 2.3
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
matrix:
  allow_failures:
    - rvm:
      - 1.9.3
      - 2.3
script: bundle exec rspec
